### ISSUE TITLE
How do you study GOAP?

### ISSUE THREAD

**Issue by DaikiMaekawa** [jsupratman13/ai_programming#2]
Hey @jsupratman13,

I saw that you contributing to the robocup team. In addition, you writing strategy scripts of python as far as I know. So, let me show you how to study GOAP if you want. :smile: 

Happy Coding!

**Comment by jsupratman13** [comment]
Thank you so much @DaikiMaekawa !

Could you correct my understanding of GOAP?
In my understanding, GOAP is basically compose of two things:
-FSM
-Astar (or any other search algorithm)
In order to connect these two, the game FEAR based their code on STRIPS model.
Is my thought correct?

**Comment by DaikiMaekawa** [comment]
Sorry for the delay.

Actually, GOAP isn't include FSM. The idea that just planning with A\* in the symbol state space given costs by each of action.

**Comment by jsupratman13** [comment]
I see. I thought of that due to the lecture I saw in the link below.
https://www.youtube.com/watch?v=rf2T_j-FlDE
In 20:36, in my understanding, GOAP doesn't use the FSM rather uses the symbol state space similar to that of FSM. Is my understanding correct?

Also this might be a little off topic but have you heard about HTN planning?

**Comment by jsupratman13** [comment]
Closing issue due to no progress
